POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date": "2019-05-05",
    "type": "HealthCheck",
    "specialist": "Rainier",
    "description": "Patient is going to die soon.",
    "diagnosisCodes": ["Z74.3"],
    "healthCheckRating": 3
}